name: Integration tests

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache bazel
        uses: actions/cache@v2
        env:
          cache-name: cache-bazel
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
      - name: Build installer
        run: bazel build //server/src/main/java/org/jetbrains/bsp/bazel:bsp-install



  integration-test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        bazel_version: ["5.4.0", "6.1.0"]
        test_target: ["//e2e:BazelBspSampleRepoTest", "//e2e:BazelBspLocalJdkTest", "//e2e:BazelBspRemoteJdkTest", "//e2e:BazelBspCppProjectTest"]
        include:
          - test_name: sample-repo-test
            test_target: //e2e:BazelBspSampleRepoTest
            java_version: 11
          - test_name: local-jdk-test
            test_target: //e2e:BazelBspLocalJdkTest
            java_version: 17
          - test_name: remote-jdk-test
            test_target: //e2e:BazelBspRemoteJdkTest
            java_version: 17
          - test_name: cpp-project-test
            test_target: //e2e:BazelBspCppProjectTest
            java_version: 11
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Cache bazel
        uses: actions/cache@v2
        env:
          cache-name: cache-bazel
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
      - name: Run test
        run: USE_BAZEL_VERSION=${{ matrix.bazel_version }} bazel run ${{ matrix.test_target }}