name: Integration tests

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache bazel
        uses: actions/cache@v2
        env:
          cache-name: cache-bazel
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
      - name: Build installer
        run: bazel build //server/src/main/java/org/jetbrains/bsp/bazel:bsp-install

  sample-repo-test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache bazel
        uses: actions/cache@v2
        env:
          cache-name: cache-bazel
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
      - name: Run test
        run: bazel run //e2e:BazelBspSampleRepoTest

#  action-graph-V1-test:
#    needs: setup
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Cache bazel
#        uses: actions/cache@v2
#        env:
#          cache-name: cache-bazel
#        with:
#          path: ~/.cache/bazel
#          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
#      - name: Run test
#        run: bazel run //e2e:BazelBspActionGraphV1Test
#
#  action-graph-V2-test:
#    runs-on: ubuntu-latest
#    needs: setup
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Cache bazel
#        uses: actions/cache@v2
#        env:
#          cache-name: cache-bazel
#        with:
#          path: ~/.cache/bazel
#          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
#      - name: Run test
#        run: bazel run //e2e:BazelBspActionGraphV2Test
#
#  java-8-project-test:
#    runs-on: ubuntu-latest
#    needs: setup
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Cache bazel
#        uses: actions/cache@v2
#        env:
#          cache-name: cache-bazel
#        with:
#          path: ~/.cache/bazel
#          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
#      - name: Run test
#        run: bazel run //e2e:BazelBspJava8ProjectTest
#
#  java-11-project-test:
#    runs-on: ubuntu-latest
#    needs: setup
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Cache bazel
#        uses: actions/cache@v2
#        env:
#          cache-name: cache-bazel
#        with:
#          path: ~/.cache/bazel
#          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
#      - name: Run test
#        run: bazel run //e2e:BazelBspJava11ProjectTest
#
#  cpp-project-test:
#    runs-on: ubuntu-latest
#    needs: setup
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Cache bazel
#        uses: actions/cache@v2
#        env:
#          cache-name: cache-bazel
#        with:
#          path: ~/.cache/bazel
#          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.sha }}
#      - name: Run test
#        run: bazel run //e2e:BazelBspCppProjectTest
